name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-app-generic.yml@8e3547c7f6d98c23095896b6097294f22100b122
    with:
      sonarOrganization: gridsuite
      sonarProjectKey: org.gridsuite:user-identity-oidc-replication-server
      dockerImage: docker.io/gridsuite/user-identity-oidc-replication-server
      dockerUsername: gridsuiteci
      eventType: user-identity-oidc-replication-server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
